# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    ubuntu_16.04:
      imageName: 'ubuntu-16.04'
    ubuntu_14.04:
      imageName: 'ubuntu-14.04'

pool:
  vmImage: $(imageName)

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    python src/python/test.py
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
